### ISSUE TITLE
Upon GAE Launcher startup, error message appears

### ISSUE THREAD

**Issue by miketheman** [rralian/StartupTemplate#3]
Using GAE Launcher 1.5.0.1099 - latest SDK.

Vanilla template, upon startup logs show this message:
```
WARNING  2011-05-27 01:04:39,405 **init**.py:851] You are using the default Django version (0.96). The default Django version will change in an App Engine release in the near future. Please call use_library() to explicitly select a Django version. For more information see http://code.google.com/appengine/docs/python/tools/libraries.html#Django
```

Why would I be using Django, if jinja templates are in use?

**Comment by rralian** [comment]
I've seen that before, but I'm not seeing it in my logs now. I'm not sure, and I haven't looked too deeply into it. Is this causing it to break for you, or are you just asking about the odd message on startup?

**Comment by miketheman** [comment]
Closing this issue, I have not used GAE in years, cannot repro for provide more details.
